# -*- coding: utf-8 -*-
"""Streamlit Installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mjUNnFZitj9LO6G11ZRmoLFYgy52tmWW
"""

!pip install -q streamlit

!pip install pyngrok

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

!ngrok authtoken 26uZqkXkVkcka4HaErnDgNxPcfg_6GqvKWGueMTjguUmGtbtH

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/app.py

